config/routes.rb
FormsUsingSurveyorGem::Application.routes.draw do
  mount Surveyor::Engine => "/surveys", :as => "surveyor"
  match "/admin/:name" => "admin#show", :as => "admin_show"
  match "/admin" => "admin#index", :as => "admin_index"

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  
  def show
    @responses = []
    survey_title = params[:name]
     @survey = Survey.where("title = '#{survey_title}'").first
     @response_set = ResponseSet.where("survey_id = #{@survey.id}")
     @response_set.each do |response|
       
     @responses += Response.where("response_set_id = #{response.id}")
   end
     
  end
  
  def index
    @surveys = Survey.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/index.html.haml
- @surveys.each do |survey|
	= link_to survey.title, admin_show_url(:name => survey.title)

app/views/admin/show.html.haml
-@responses.each do |response|
	.key
		= response.question.text
	.value
		= response.datetime_value
		= response.text_value
		
= link_to "return to all surveys", admin_index_url

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FormsUsingSurveyorGem</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>